[build-system]
requires = ["flit_core >=3.11,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "slurm_scripts"
authors = []
license = "MIT"
license-files = ["LICENSE"]
dynamic = ["version", "description"]

[project.scripts]
sh2sjob = "slurm_scripts:cli_run_slurm_script"
sh2sarray = "slurm_scripts:cli_run_slurm_array"
cmd2sjob = "slurm_scripts:cli_run_command_to_slurm_job"